// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfDOY8aB1xAB2yeB_vvtCtKR70aEaJxG8',
    appId: '1:19827656414:web:f757fa9e31c358558ce44f',
    messagingSenderId: '19827656414',
    projectId: 'aroggyapath',
    authDomain: 'aroggyapath.firebaseapp.com',
    storageBucket: 'aroggyapath.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSc2KNUz5ihD0bLwObGd9OkV4NO0Mp9qE',
    appId: '1:19827656414:android:51d3e4eaf3edb1898ce44f',
    messagingSenderId: '19827656414',
    projectId: 'aroggyapath',
    storageBucket: 'aroggyapath.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABW3TALpSQk4NWT0hw3WF5Xlqq8bZV0ME',
    appId: '1:19827656414:ios:4f598b956a0cc3608ce44f',
    messagingSenderId: '19827656414',
    projectId: 'aroggyapath',
    storageBucket: 'aroggyapath.firebasestorage.app',
    iosBundleId: 'com.example.aroggyapath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABW3TALpSQk4NWT0hw3WF5Xlqq8bZV0ME',
    appId: '1:19827656414:ios:4f598b956a0cc3608ce44f',
    messagingSenderId: '19827656414',
    projectId: 'aroggyapath',
    storageBucket: 'aroggyapath.firebasestorage.app',
    iosBundleId: 'com.example.aroggyapath',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfDOY8aB1xAB2yeB_vvtCtKR70aEaJxG8',
    appId: '1:19827656414:web:e60263f98b03e4478ce44f',
    messagingSenderId: '19827656414',
    projectId: 'aroggyapath',
    authDomain: 'aroggyapath.firebaseapp.com',
    storageBucket: 'aroggyapath.firebasestorage.app',
  );
}
